Update build-app.yml

diff --git a/.github/workflows/build-app.yml b/.github/workflows/build-app.yml
--- a/.github/workflows/build-app.yml
+++ b/.github/workflows/build-app.yml
@@ -51,12 +51,19 @@ jobs:
           dockerhub-user: ayobamiblackforce
           dockerhub-password: ${{ vars.DOCKERHUB_TOKEN }}
 
+      # - name: OWASP ZAP Full Scan
+      #   #uses: zaproxy/action-baseline@v0.10.0
+      #   uses: zaproxy/action-full-scan@v0.8.0
+      #   with:
+      #     target: 'http://${{ steps.con_ip.outputs.value }}:8501'
+      #     fail_action: false      
+
+
       - name: OWASP ZAP Full Scan
-        #uses: zaproxy/action-baseline@v0.10.0
-        uses: zaproxy/action-full-scan@v0.8.0
-        with:
-          target: 'http://${{ steps.con_ip.outputs.value }}:8501'
-          fail_action: false      
+        run: |
+          docker run -v /home/runner/work/guessing-game-ayo/guessing-game-ayo:/zap/wrk/:rw --network=host \
+          -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -t ghcr.io/zaproxy/zaproxy:stable \
+          zap-full-scan.py -t http://${{ steps.con_ip.outputs.value }}:8501 -J report_json.json -w report_md.md -r report_html.html || true
 
       - name: Upload ZAP Report
         uses: actions/upload-artifact@v4
@@ -64,18 +71,11 @@ jobs:
         with:
           name: json_zap-report
           path: report_html.html
-
-
+          
       - name: push to repo
         run: |
           echo ${{ vars.DOCKERHUB_TOKEN }} | docker login -u ayobamiblackforce --password-stdin
           docker push ayobamiblackforce/guessing-game-staging:${{ steps.image_tag.outputs.value }}
-
-      # - name: jjj
-      #   run: |
-      #     docker run -v /home/runner/work/guessing-game-ayo/guessing-game-ayo:/zap/wrk/:rw --network=host \
-      #     -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -t ghcr.io/zaproxy/zaproxy:stable \
-      #     zap-full-scan.py -t http://172.17.0.2:8501 -J report_json.json -w report_md.md -r report_html.html
 
       # cmd_options: '-z "-config globalalertfilter=High"'
           
